version: '3'

services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: my_secret_password
      MARIADB_DATABASE: app_db
      MARIADB_USER: db_user
      MARIADB_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: